// Generated by CoffeeScript 1.6.3
var compile, file, ipso, join, list, lstatSync, path, program, readFileSync, _ref;

program = require('commander');

_ref = require('fs'), readFileSync = _ref.readFileSync, lstatSync = _ref.lstatSync;

join = require('path').join;

compile = require('coffee-script').compile;

program.version(JSON.parse(readFileSync(__dirname + '/../package.json'), 'utf8').version);

program.option('-f, --file [file]', 'Run file.');

file = program.parse(process.argv).file;

ipso = require('ipso').components();

if (file[0] !== '/') {
  path = join(process.cwd(), file);
}

if (path.match(/\.coffee$/)) {
  list = eval(compile(readFileSync(path, 'utf8'), {
    bare: true
  }));
} else if (path.match(/\.js$/)) {
  list = eval("list = { " + (readFileSync(path, 'utf8')) + " }");
}

setInterval((function() {
  var text, _results;
  _results = [];
  for (text in list) {
    _results.push(console.log('%s:', text, list[text]()));
  }
  return _results;
}), 1000);
