// Generated by CoffeeScript 1.6.3
var file, ipso, join, path, program, readFileSync;

program = require('commander');

readFileSync = require('fs').readFileSync;

join = require('path').join;

program.version(JSON.parse(readFileSync(__dirname + '/../package.json'), 'utf8').version);

program.option('-f, --file [file]', 'Run file.');

file = program.parse(process.argv).file;

ipso = require('ipso').components();

if (file[0] !== '/') {
  path = join(process.cwd(), file);
}

require(path);
